spring.application.name=voice-agent

spring.datasource.url=jdbc:mysql://localhost:3306/voice_ai_db
spring.datasource.username=root
spring.datasource.password=mysqlkunu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=voiceaiagent245@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# JWT
jwt.secret=8f4d2a91c7e64b13a9d5f82e6c1b7a93f0d4e8c2a6b9f1d7e3c5a8b2d6f9e4c1
jwt.expiration=86400000